[tool.poetry]
name = "gil-tutorial"
version = "0.1.0"
description = ""
authors = ["leblancr <rich.leblanc1@proton.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
